In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("Superstore_Sales.csv")
df.head()

   Order Date Region         Category  Sales  Profit
0  2024-01-05   West       Technology  55000    8000
1  2024-01-12   East        Furniture  12000    1500
2  2024-01-18  South  Office Supplies   8000    1200
3  2024-02-03   West        Furniture  15000    2000
4  2024-02-15  North       Technology  30000    5000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  28 non-null     object
 1   Region      28 non-null     object
 2   Category    28 non-null     object
 3   Sales       28 non-null     int64
 4   Profit      28 non-null     int64
dtypes: int64(2), object(3)
memory usage: 856.0+ bytes

In [7]:
df.isnull().sum()

Order Date    0
Region        0
Category      0
Sales         0
Profit        0
dtype: int64

In [8]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [9]:
df["Month-Year"] = df["Order Date"].dt.to_period("M")

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["Region"] = df["Region"].str.strip()
df["Category"] = df["Category"].str.strip()

In [12]:
df = df.drop_duplicates()

In [13]:
df["Region"] = df["Region"].str.title()
df["Category"] = df["Category"].str.title()

In [14]:
df[df["Sales"] < 0]
df[df["Profit"] < 0]

Empty DataFrame
Columns: [Order Date, Region, Category, Sales, Profit, Month-Year]
Index: []

In [15]:
df = df[df["Sales"] >= 0]

In [16]:
df["Profit Margin %"] = (df["Profit"] / df["Sales"]) * 100

In [17]:
df.describe()

,Order Date,Sales,Profit,Profit Margin %
count,28,28.000000,28.000000,28.000000
mean,2024-06-09 15:25:42.857142784,23757.142857,3630.357143,14.246386
min,2024-01-05 00:00:00,6000.000000,800.000000,11.764706
25%,2024-03-14 00:00:00,9875.000000,1200.000000,12.800752
50%,2024-05-28 00:00:00,15500.000000,2050.000000,13.333333
75%,2024-09-05 18:00:00,38500.000000,6275.000000,16.266447
max,2024-12-18 00:00:00,60000.000000,9500.000000,17.142857
std,NaN,16821.380323,2880.886543,1.864405

In [18]:
df.dtypes

Order Date         datetime64[ns]
Region                     object
Category                   object
Sales                       int64
Profit                      int64
Month-Year              period[M]
Profit Margin %           float64
dtype: object

In [19]:
df["Quarter"] = df["Order Date"].dt.quarter

In [20]:
df.groupby("Region")[["Sales","Profit"]].sum()

         Sales  Profit
Region
East    154000   23000
North   150000   23700
South   118700   17650
West    242500   37300

In [21]:
df.to_csv("Final_Cleaned_Superstore.csv", index=False)

In [26]:
df.to_csv("Final_Cleaned_Superstore.csv", index=False)

In [27]:
from IPython.display import FileLink
FileLink("Final_Cleaned_Superstore.csv")

/drive/notebooks/Final_Cleaned_Superstore.csv